### ISSUE TITLE
Trying to run Vault of the Vindicator drops back to shell

### ISSUE THREAD

**Issue by m00dawg** [irmen/cx16shell#3]
When using cx16-shell as AUTOBOOT.X16 I'm running into an issue where VooV doesn't seem to want to run. It does run if I don't boot into the shell however so I know the program works. Here's all the things I did in the shell:

```
cd games
cd vindicator
vault
```

Trying vault,VAULT, VAULT.PRG, and vault.prg all seem to do the same thing - it tries to load, shows something on the screen very briefly (I can't see what it is) then drops back to shell. It's a warm shell though - system didn't fully restart since I'm in the same directory (so running `ls` shows me the files I expect to see in the 'vindicator' directory.

**Comment by irmen** [comment]
quite odd, as the shell uses regular basic LOAD"thing" + RUN commands to actually load and run the program. Could it be that you have a directory named "vault" in there as well somehow?

**Comment by m00dawg** [comment]
Nope. I do have Chase Vault on the card but it's under "CHASVALT". Here's all the vaultly named items:

```tim@lindawg /media/tim/CX16-DEV-SD $ find ./ -iname vault*
./GAMES/VINDICATOR/vault.prg
tim@lindawg /media/tim/CX16-DEV-SD $ 
```

I agree it's quite weird. I launch things from cx16-shell all the time and this is the first that seems to have caused issues. I tried launching a buncha stuff I don't normally launch and haven't had any issues with other programs. Just in case I renamed 'VAULT.PRG' to 'THING.PRG' and tried that but same result.

**Comment by irmen** [comment]
It's got something to do with the fact that the program is called "vault.prg" in lowercase.
This gets translated into the wrong characters when the shell is printing the LOAD command, somehow.

Should work if you rename it to VAULT.PRG on the disk. Can you try that?

**Comment by m00dawg** [comment]
Apologies for missing the comment! I actually did try it both ways (vault.prg and VAULT.PRG). Normally either works when launching a program but in this case both produce the same issue. My previous comment wasn't very clear there.

**Comment by adiee5** [comment]
@m00dawg could you possibly send us the program? I'd probably helpful

**Comment by irmen** [comment]
I think the latest commit fixes the problem.

**Comment by irmen** [comment]
@m00dawg can you confirm that it was fixed and close this if true?
