### ISSUE TITLE
`vi` should be renamed `pico` or `nano`

### ISSUE THREAD

**Issue by oodler577** [irmen/cx16shell#4]
The ux for this editor is a workalike to `nano` as the kids know it (clone of `pico`); in any case it's a small nit but also a surprise when I opened it up and it was basically nano. I'll surely take it, but it's going to be confusing to a lot of people drawn to this shell. Overall, this shell is awesome. TY.

**Comment by adiee5** [comment]
Yeah, the dude is right, x16 edit, that got merged into kernal and what this shell is using is based on unix' nano

**Comment by irmen** [comment]
"why not both" Is how I think this can be solved !

**Comment by adiee5** [comment]
Sounds reasonable

**Comment by oodler577** [comment]
> both

A modal editor with basic `vi` bindings would be a nice stretch goal for me to accomplish in 2024 😆.

**Comment by adiee5** [comment]
Maybe some one'll make vim for cx16....

But not me, I don't even use that on linux, let alone on anything else

**Comment by oodler577** [comment]
WIP, but necro posting for future generations to appreciate - https://github.com/oodler577/VICL1
