### ISSUE TITLE
Scrolling the cursor outside the command area, then return, your command will always register as invalid

### ISSUE THREAD

**Issue by ToboterXP** [irmen/cx16shell#5]
This also happens if you scroll to a different line, where it will continue to happen until the cursor reaches the bottom of the screen

**Comment by tomxp411** [comment]
Suggested workaround in the shell: 

1. Check the first character of the command. If it is $ or space, then trim that character
2. Repeat until the first character in the command is neither $ or space.

**Comment by irmen** [comment]
what about filtering out cursor up/down keys from the input?  There's no reason to be able to move the cursor around the screen

**Comment by adiee5** [comment]
> what about filtering out cursor up/down keys from the input?  There's no reason to be able to move the cursor around the screen
> 
> the filename entry box in the Paint tool does this too 

Yeah, you should do that if you know how. I though the reason this wasn't done yet is because you didn't know how to do that

**Comment by adiee5** [comment]
Meanwhile up and down keys could be used for selecting previous commands, like on other shells out there

**Comment by irmen** [comment]
The command history indeed is something that could be added at a later point perhaps.  I mean, there's little other use for the cursor up/down keys in a program like this, I suppose.
