### ISSUE TITLE
num doesn't recognize C-Style prefixes, despite claiming to recognize all prefixes

### ISSUE THREAD

**Issue by ToboterXP** [irmen/cx16shell#7]
Both 0x123 and 0b01010 get read as 0

**Comment by adiee5** [comment]
Does it work with 6502/Prog8 style prefixes?

**Comment by irmen** [comment]
Yes it does, and it uses a prog8 library function for this that I have no intention of teaching various other prefixes beside the well-known assembly ones.  So I'm going to clarify  the help message ;)
