### ISSUE TITLE
Suggestion: add "dir" as an alias for "ls"

### ISSUE THREAD

**Issue by tomxp411** [irmen/cx16shell#8]
Those of us who grew up in the Wintel world are used to typing "DIR" to get a directory listing. I have 30 years of muscle memory to overcome, and even on Linux, I've noticed that many distros now alias dir to ls, sometimes even changing the format to be more DOS-like (-aL is my favorite.)

Adding "dir" would make things much easier for DOS users. This can be functionally equivalent to "ls"; just another spelling for the same command.

**Comment by adiee5** [comment]
It would be rather easy
